<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Shritik_Sharma" failures="1" tests="3" name="Register Test " time="40.715" errors="0" timestamp="2025-05-14T00:47:08 IST">
  <testcase classname="automationPractice.base.RegisterUser" name="loginWithCorrectEmailnPass" time="5.747"/>
  <testcase classname="automationPractice.base.RegisterUser" name="loginWithCorrectEmailnPass" time="5.256"/>
  <testcase classname="automationPractice.base.RegisterUser" name="logout" time="1.51">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Customer has not logged out expected [Loginto your account] but found [Login to your account]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Customer has not logged out expected [Loginto your account] but found [Login to your account]
at automationPractice.base.RegisterUser.logout(RegisterUser.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- logout -->
</testsuite> <!-- Register Test  -->
